created CustomUser model
Danil1024/Tournament-WebSite pull request #2
Opened 2024-12-06 06:58 UTC by Danil1024

2024-12-11 12:02 UTC, Yarik192 commented on tournament_web_site/profile_user/models.py
> +    email = models.EmailField(unique=True, verbose_name='Почта', blank=False, null=False) # Уникальная почта
почта уже есть у юзера

2024-12-11 12:05 UTC, Yarik192 requested changes

2024-12-12 13:09 UTC, Yarik192 commented on requirements.txt
так тут нет Pillow

2024-12-12 13:10 UTC, Yarik192 commented on tournament_web_site/profile_user/admin.py
> +	list_display = ['username', 'email', 'age', 'avatar']
ты уверен что хочешь там видеть аватар каждого клиента ? 
это ж просто будет в списке всех юзеров отображаться

2024-12-12 13:12 UTC, Yarik192 commented on tournament_web_site/profile_user/models.py
> +        return self.username
правило хорошего тона, лучше облагородить в str() или в ф-строку

2024-12-12 13:12 UTC, Yarik192 commented on tournament_web_site/profile_user/models.py
> +    REQUIRED_FIELDS = ['email'] # Обязательные поля при создании пользователя, кроме логина и пароля
оно по дефолту вроде как уже обязательно глянь пожалуйста в доке, могу ошибатьяс

2024-12-12 13:12 UTC, Yarik192 commented on tournament_web_site/profile_user/models.py
> +    USERNAME_FIELD = 'username'
и это тоже дефолтное значение по идее

2024-12-12 14:02 UTC, Danil1024 commented on tournament_web_site/profile_user/admin.py
> +	list_display = ['username', 'email', 'age', 'avatar']
да! Почему нет?

2024-12-12 14:03 UTC, Yarik192 commented on tournament_web_site/profile_user/admin.py
> +	list_display = ['username', 'email', 'age', 'avatar']
да оно просто громоздкое наверное будет, но как хочешь

2024-12-12 14:39 UTC, Yarik192 commented on tournament_web_site/profile_user/models.py
> +    avatar = models.ImageField(upload_to='avatars/', verbose_name='Аватарка', blank=True, null=True) # Поле для загрузки изображения, путь к картинкам - avatars/
надо создать папку media и в ней создать папку avatars

2024-12-12 14:40 UTC, Yarik192 commented on tournament_web_site/profile_user/models.py
> +        return f'self.username'
а ты тестишь ?

2024-12-12 14:43 UTC, Yarik192 approved these changes

2024-12-13 15:48 UTC, Yarik192 commented on tournament_web_site/tournament_web_site/settings.py
> +AUTH_USER_MODEL = "profile_user.CustomUser"
давай придерживаться одного стиля, в плане скобок

2025-01-11 13:57 UTC, merged